[pytest]
addopts = -vs -ra -p no:warnings
;testpaths = tests/

python_files = test_*.py
python_classes = *TestSuite
python_functions = start test_*


log_cli = 1
log_cli_level = INFO
log_cli_date_format = %Y-%m-%d %H:%M:%S
log_cli_format = %(asctime)s - [%(processName)s:%(threadName)s] - %(filename)s - %(lineno)d - %(levelname)s - %(message)s
log_file = pytest.log
log_file_level = DEBUG
log_file_date_format = %Y-%m-%d %H:%M:%S
log_file_format = %(asctime)s - [%(processName)s:%(threadName)s] - %(filename)s - %(lineno)d - %(levelname)s - %(message)s

markers =
    p0
    p1
    p2
